/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EPAM_JAVA;


public class App {
    public String getGreeting() {
        return "Hello world1.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
