/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EPAM_JAVA;

import AppInterface.Window;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello world1.";
    }

    public static void main(String[] args) {

        Logger logger = LoggerFactory.getLogger(App.class);
        logger.info("\n\n\nLogger is working");
        logger.trace("Trace");
        logger.debug("Debug");
        logger.warn("Warn");
        logger.error("Error");

        try {
            Window.runApplication();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
